service: aaras-lambda-perfs

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
package:
  exclude:
    - ./**
  individually: true
functions:
  ruby25:
    runtime: ruby2.5
    handler: ruby25/handler.hello
    package:
      include:
        - ruby25/handler.rb
    events:
      - http:
          path: /ruby25
          method: get